# Step 1: Build the binary
FROM golang:1.25.0-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main .

# Step 2: Run the binary
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
# Expose the port your Gin/Huma app uses (e.g., 8080)
EXPOSE 8090
CMD ["./main"]